### ISSUE TITLE
アイデア出し

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/hack-festival-2019#3]
# Make Fukuoka わくわく
福岡がもっとワクワクする街にするには

**Comment by rkdora** [comment]
ターゲットをどうするか
県民or観光客

**Comment by rkdora** [comment]
福岡の魅力
https://yokanavi.com/appeal/

アジアの玄関口
食事が美味しい街ランキング　政令市2位
アジアの屋台都市10選　国内で福岡のみ

**Comment by tanacchi** [comment]
輩をたおす

**Comment by tanacchi** [comment]
場所特定するゲーム

**Comment by rkdora** [comment]
ラーメン屋に特化した紹介

**Comment by tanacchi** [comment]
スペワ再現

**Comment by tanacchi** [comment]
卍きせかえゲーム

**Comment by tanacchi** [comment]
ラーメン特化型のサービス

**Comment by tanacchi** [comment]
ロケ地拾得

**Comment by syu-kwsk** [comment]
らーめん大盛り判定

**Comment by syu-kwsk** [comment]
福岡の魅力を知りながら輩も倒せるゲーム

**Comment by rkdora** [comment]
目的「地域活性化」
地域同士切磋琢磨することで活発化。
地域の特産が出てくることにより、互いの地域の魅力を知ることができる。

**Comment by rkdora** [comment]
クイズ形式

**Comment by rkdora** [comment]
# leap motionの強み
- 非接触入力デバイス
- ジェスチャー認識

**Comment by tanacchi** [comment]
福岡のものかどうか判定するゲームになりました
