### ISSUE TITLE
フリー素材

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/hack-festival-2019#4]
# 福岡関連

- [x] ラーメン

- [x] 明太子

- [ ] 三池炭鉱

- [x] 太宰府天満宮

- [x] 博多ポートタワー

- [x] 鉄なべ

- [x] 糸島

- [ ] ブリヂストン

- [ ] TOTO

- [ ] 安川電機

- [x] ソフトバンクホークス

- [ ] ジャー坊（大牟田ゆるキャラ）

- [ ] くるっぱ（久留米ゆるキャラ）

**Comment by rkdora** [comment]
- [ ] 大砲ラーメン

- [ ] shinshin

- [ ] だるま

**Comment by syu-kwsk** [comment]
![caste_men](https://user-images.githubusercontent.com/39556764/54075872-b864c080-42e7-11e9-9526-c438ff3aa2c9.png)
![money_single_mother_poor](https://user-images.githubusercontent.com/39556764/54075876-bf8bce80-42e7-11e9-807e-56a192a5851f.png)
![creditcard_syakkin](https://user-images.githubusercontent.com/39556764/54075878-c4e91900-42e7-11e9-8288-93e5c447ab4a.png)
![school_furyou_tsuppari](https://user-images.githubusercontent.com/39556764/54075880-c61a4600-42e7-11e9-9bcf-fcc68cc6e084.png)
![mild_yankee_dqn](https://user-images.githubusercontent.com/39556764/54075881-c7e40980-42e7-11e9-9bc4-7120558f54f5.png)
![furyo_shounen](https://user-images.githubusercontent.com/39556764/54075882-c9153680-42e7-11e9-9637-7bff78d098e4.png)

**Comment by tanacchi** [comment]
GJ
