### ISSUE TITLE
Let's 卍

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/hack-festival-2019#5]
# Let's 卍
「福岡のもの」か「福岡以外のもの」に仕分けるゲーム。

## 目的
福岡に対する理解を深めることで、地域の活性化につながる。

## 入力デバイス
Leap Motion

## 詳細
「福岡のもの」に関する画像が表示されたときは、スワイプジェスチャーを行う。
「福岡以外のもの」に関する画像が表示されたときは、スクリーンタップジェスチャーを行う。

**Comment by rkdora** [comment]
ゲーム時間　30秒
時間内の到達スコアを競う。
正しいジェスチャーは加点（+10p）。誤ったジェスチャーは減点(-5p)。

**Comment by syu-kwsk** [comment]
# ストーリー
 自分は福岡県民代表で、卍から福岡県知識対決を挑まれる。
勝負して勝った場合⇒卍と仲良くなり、県民と卍の集合写真がラストシーン
勝負して負けた場合⇒卍にボコされて、卍に支配される集合写真がラストシーン

**Comment by rkdora** [comment]
# オープニング
Let's 卍
ある日、地元の卍から果し状を突きつけられた！
「おれとおまえの福岡愛、どっちが強いか勝負だ！もし、おれに勝てたらいっしょに福岡を盛り上げていこう！ただ、もし俺が勝ったら・・・おれが頭だ！」
さあ、がんばれ！！

**Comment by rkdora** [comment]
# エンディング
## 成功
君の福岡に対する理解度はすばらしい！
ぜひ、一緒に福岡を盛り上げていこう！

## 失敗
まだまだだ、でなおしてこい！（爆発音）

**Comment by tanacchi** [comment]
優勝おめでとうございました
